### ISSUE TITLE
TCK with CRDT Support

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#24]
As with issue https://github.com/cloudstateio/cloudstate/issues/316 started, this issue is about to have TCK support for CRDT state models.

The story so far is to have synthetic TCK test cases and possibly a human consumable use case like a shopping cart or the like. The linked issue should discuss that. The primary focus with this issue is on complete coverage through synthetic TCK tests.

**Sub-Tasks**
- [x] CRDT Tests for Commands
  - [x] GCounter
  - [x] PNCounter
  - [x] GSet
  - [x] ORSet
  - [x] Flag
  - [x] LWWRegister
  - [x] ORMap
  - [x] Vote
- [x] CRDT Tests for Streamed Commands
- [x] CRDT TCK Service (synthetic)
- [x] ~verify entity passivation~ => done by main TCK
- [x] ~provide an implementation for JS- or Java-Support~ => done by main TCK

**Comment by marcellanz** [comment]
Will be substituted by functional tests for v0.2.x but held as a separate Issue outside of this milestone.
