### ISSUE TITLE
CRDT – port dapr-contrib cloudstate state component

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#32]
Port the [dapr contrib cloudstate](https://github.com/dapr/components-contrib/tree/master/state/cloudstate) state component as an exemplary use of the new CRDT support.

**Tasks**

- [x] port
- [ ] improve tests. currently not much is tested.
- [ ] #30 and #31 will be needed to complete the port.
- [ ]  check and clear any existing incompatibilities with the embedded pb filedescriptor the state component uses/used.

I'm working on this. WIP branch:
https://github.com/mrcllnz/components-contrib/tree/feature/cloudstate_crdt_support
