### ISSUE TITLE
samples - part the shopping cart for samples-go-shoppingcart

### ISSUE THREAD

**Issue by marcellanz** [cloudstateio/go-support#33]
**Tasks**
- [x] add the sample repository: samples-go-shoppingcart.
- [ ] part the shopping cart example from the Go TCK.
- [ ] find a story to have the shopping cart only once, TCK and sample, and still use it as tested sourcecode in the docs.

**Comment by marcellanz** [comment]
@pvlugter what do you think about a samples repository for the go shopping cart?

**Comment by sleipnir** [comment]
@marcellanz Today, most languages have their own examples as part of their own repository. Do you think this is not appropriate? My opinion is that, or we have a single repository of examples for all supported languages, this would make it easier for the user, as it is a unique contact surface for all languages and all examples of supported types, on the other hand, makes it difficult to maintenance. Or the examples of each language reside in its own language repository, which gives the user interested in a language access to everything related to that support language.

**Comment by marcellanz** [comment]
@sleipnir I'm open for any form that is in line with the project in large. 

My motivation is on one side to part the TCK shopping cart and a properly documented example shopping cart. If someone wants to implement or try out the shopping cart not having to clone the user support library as a whole and then getting confused about what she got. Beside that, I'm planning to have at least [two go modules](https://github.com/cloudstateio/go-support/issues/23) for the TCK part and also the library part, also so that users don't have to `go get` the TCK code when they use the Go support.

Saying that I see also a growing count of `samples-XYZ` libraries under the main project:
- https://github.com/cloudstateio/samples-java-shoppingcart
- https://github.com/cloudstateio/samples-js-shoppingcart
- https://github.com/cloudstateio/samples-ts-shoppingcart
- https://github.com/cloudstateio/samples-ui-shoppingcart
- https://github.com/cloudstateio/samples-js-chat
- https://github.com/cloudstateio/samples-java-chat

all recently updated with developer friendly documentation. I'm open to any form to have examples that is appropriate and I'm happy for any insights how we should have a consistent collection of samples.

**Comment by sleipnir** [comment]
I think the examples you mentioned are from LBS.
Okay, I hope the best for the project too.
I just think that having a collection of examples spread around is not a good approach, but if the majority decides to do so. The best for everyone is the best for me.

**Comment by marcellanz** [comment]
yeah, see my initial question for Peter.

**Comment by sleipnir** [comment]
I saw. I just wanted to leave my opinion on record

**Comment by marcellanz** [comment]
Perfect @sleipnir, thank you. lets discuss it.

**Comment by pvlugter** [comment]
Since it's the pattern we're using currently, I've created [samples-go-shoppingcart](https://github.com/cloudstateio/samples-go-shoppingcart)

I'm also not sure that having all the samples in separate repos is the best approach. I think having samples within the language support repos is easier to maintain, and they can evolve along with the language support. We can always publish zips of the samples to download and try, linked from the docs, instead of git cloning.

**Comment by marcellanz** [comment]
Thanks @pvlugter. I agree regarding maintaining the samples. The shopping cart source is visible on three places now; and all of them need verified sources:
- the TCK shoppingcart
- `/docs` samples 
- sample application to be downloaded by developers

I'd prefer to have no paradox tags like
```
//#compose-entity
//#entity-type
```

in the source used for the sample application. And even could `copy-clean` them for the samples repository or any zip file later but always coming from a single source if possible.
